In [1]:
import pandas as pd

df_coisa = pd.read_csv("dados/bu_mz.csv")
display(df_coisa)

,ID_Venda,Data,Cliente,Provincia,Produto,Categoria,Preco,Quantidade,Metodo_Pagamento
0,1,2025-01-05,Carlos,Maputo,Laptop,Eletronicos,45000,1,M-Pesa
1,2,2025-01-07,Ana,Sofala,Mouse,Eletronicos,800,2,E-Mola
2,3,2025-01-09,Joao,Nampula,Cadeira,Moveis,3500,1,Cartao
3,4,2025-01-12,Mariana,Maputo,Secretaria,Moveis,7000,1,M-Pesa
4,5,2025-01-15,Paulo,Gaza,Tablet,Eletronicos,20000,1,Cartao
5,6,2025-01-18,Celia,Tete,Armario,Moveis,15000,1,E-Mola
6,7,2025-01-20,Bruno,Maputo,Laptop,Eletronicos,47000,1,M-Pesa
7,8,2025-01-22,Sara,Nampula,Mouse,Eletronicos,900,3,Cartao
8,9,2025-01-24,Tomás,Sofala,Mesa,Moveis,6000,1,M-Pesa
9,10,2025-01-27,Luis,Maputo,Tablet,Eletronicos,21000,2,Cartao

In [2]:
total_vendas = len(df_coisa)
print("Total de vendas: ", total_vendas)
display(list(df_coisa.columns))
display(df_coisa.head())

Total de vendas:  10

['ID_Venda',
 'Data',
 'Cliente',
 'Provincia',
 'Produto',
 'Categoria',
 'Preco',
 'Quantidade',
 'Metodo_Pagamento']

,ID_Venda,Data,Cliente,Provincia,Produto,Categoria,Preco,Quantidade,Metodo_Pagamento
0,1,2025-01-05,Carlos,Maputo,Laptop,Eletronicos,45000,1,M-Pesa
1,2,2025-01-07,Ana,Sofala,Mouse,Eletronicos,800,2,E-Mola
2,3,2025-01-09,Joao,Nampula,Cadeira,Moveis,3500,1,Cartao
3,4,2025-01-12,Mariana,Maputo,Secretaria,Moveis,7000,1,M-Pesa
4,5,2025-01-15,Paulo,Gaza,Tablet,Eletronicos,20000,1,Cartao

In [3]:
df_coisa["Total"] = df_coisa["Preco"] * df_coisa["Quantidade"]
display(df_coisa)

,ID_Venda,Data,Cliente,Provincia,Produto,Categoria,Preco,Quantidade,Metodo_Pagamento,Total
0,1,2025-01-05,Carlos,Maputo,Laptop,Eletronicos,45000,1,M-Pesa,45000
1,2,2025-01-07,Ana,Sofala,Mouse,Eletronicos,800,2,E-Mola,1600
2,3,2025-01-09,Joao,Nampula,Cadeira,Moveis,3500,1,Cartao,3500
3,4,2025-01-12,Mariana,Maputo,Secretaria,Moveis,7000,1,M-Pesa,7000
4,5,2025-01-15,Paulo,Gaza,Tablet,Eletronicos,20000,1,Cartao,20000
5,6,2025-01-18,Celia,Tete,Armario,Moveis,15000,1,E-Mola,15000
6,7,2025-01-20,Bruno,Maputo,Laptop,Eletronicos,47000,1,M-Pesa,47000
7,8,2025-01-22,Sara,Nampula,Mouse,Eletronicos,900,3,Cartao,2700
8,9,2025-01-24,Tomás,Sofala,Mesa,Moveis,6000,1,M-Pesa,6000
9,10,2025-01-27,Luis,Maputo,Tablet,Eletronicos,21000,2,Cartao,42000

In [4]:
soma_coluna = df_coisa["Total"].sum()
media_total = df_coisa["Total"].median()

print("Total :", soma_coluna, "Media: ", media_total)

Total : 189800 Media:  11000.0

In [5]:
analise = df_coisa[["Provincia", "Total"]].groupby("Provincia").sum()
analise = analise.sort_values(by="Total", ascending=False)

display(analise)

            Total
Provincia
Maputo     141000
Gaza        20000
Tete        15000
Sofala       7600
Nampula      6200

In [6]:
analise_1 = df_coisa[["Produto", "Total"]].groupby("Produto").sum()
analise_1 = analise_1.sort_values(by="Total", ascending=False)

display(analise_1)
analise_total = analise_1["Total"].sum()
print("O total é: ", analise_total)

            Total
Produto
Laptop      92000
Tablet      62000
Armario     15000
Secretaria   7000
Mesa         6000
Mouse        4300
Cadeira      3500

O total é:  189800

In [7]:
df_maputo = df_coisa[df_coisa["Provincia"] == "Maputo"]
display(df_maputo)

,ID_Venda,Data,Cliente,Provincia,Produto,Categoria,Preco,Quantidade,Metodo_Pagamento,Total
0,1,2025-01-05,Carlos,Maputo,Laptop,Eletronicos,45000,1,M-Pesa,45000
3,4,2025-01-12,Mariana,Maputo,Secretaria,Moveis,7000,1,M-Pesa,7000
6,7,2025-01-20,Bruno,Maputo,Laptop,Eletronicos,47000,1,M-Pesa,47000
9,10,2025-01-27,Luis,Maputo,Tablet,Eletronicos,21000,2,Cartao,42000

In [8]:
df_maior_1 = df_coisa[df_coisa["Quantidade"] > 1]
display(df_maior_1)

,ID_Venda,Data,Cliente,Provincia,Produto,Categoria,Preco,Quantidade,Metodo_Pagamento,Total
1,2,2025-01-07,Ana,Sofala,Mouse,Eletronicos,800,2,E-Mola,1600
7,8,2025-01-22,Sara,Nampula,Mouse,Eletronicos,900,3,Cartao,2700
9,10,2025-01-27,Luis,Maputo,Tablet,Eletronicos,21000,2,Cartao,42000

In [9]:
pagamentos = df_coisa["Metodo_Pagamento"].value_counts()
pagamentos.sort_values(ascending=False)
display(pagamentos)

Metodo_Pagamento
M-Pesa    4
Cartao    4
E-Mola    2
Name: count, dtype: int64

In [10]:
df_coisa["Total"] = df_coisa["Preco"] * df_coisa["Quantidade"]
receita_categoria = df_coisa.groupby("Categoria")["Total"].sum()
receita_categoria.sort_values(ascending=False)
display(receita_categoria)

Categoria
Eletronicos    158300
Moveis          31500
Name: Total, dtype: int64

In [11]:
df_coisa.loc[df_coisa["Total"].idxmax()]
df_coisa.loc[df_coisa["Total"].idxmin()]

ID_Venda                      2
Data                 2025-01-07
Cliente                     Ana
Provincia                Sofala
Produto                   Mouse
Categoria           Eletronicos
Preco                       800
Quantidade                    2
Metodo_Pagamento         E-Mola
Total                      1600
Name: 1, dtype: object

In [12]:
pc = df_coisa.groupby(['Provincia', 'Categoria']) ['Total'].sum()
pc = pc.sort_values(ascending=False)
display(pc)

Provincia  Categoria
Maputo     Eletronicos    134000
Gaza       Eletronicos     20000
Tete       Moveis          15000
Maputo     Moveis           7000
Sofala     Moveis           6000
Nampula    Moveis           3500
           Eletronicos      2700
Sofala     Eletronicos      1600
Name: Total, dtype: int64

In [13]:
# Filtrar apenas a categoria 'Electronicos'

df_e = df_coisa[df_coisa["Categoria"] == 'Eletronicos']

#Agrupar provincias e somar totais

prov = df_e.groupby('Provincia') ['Total'].sum()

# Ordenar de maior para menor

prov = prov.sort_values(ascending=False)
display(prov)

Provincia
Maputo     134000
Gaza        20000
Nampula      2700
Sofala       1600
Name: Total, dtype: int64

In [14]:
df_m = df_coisa[df_coisa["Categoria"] == "Eletronicos"]
man = df_m.groupby("Provincia") ['Total'].sum()
display(man)

Provincia
Gaza        20000
Maputo     134000
Nampula      2700
Sofala       1600
Name: Total, dtype: int64

In [18]:
df_resumo = pd.DataFrame({
    "Item": ["Soma do total de vendas", "Media do total de vendas", "Total de vendas"],
    "Resultado": [ soma_coluna, media_total, total_vendas]
})

In [ ]:
from fpdf import FPDF
import os

def gerar_pdf_resumo(df_resumo, nome_arquivo, titulo="Projecto Portfolio - CodeNest"):
    pdf = FPDF()
    pdf.add_page()
    
    # Título
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, titulo, ln=True, align="C")
    pdf.ln(10)

    # Corpo do resumo
    pdf.set_font("Arial", "", 12)
    
    for index, row in df_resumo.iterrows():
        linha = f"{row['Item']}: {row['Resultado']}"
        pdf.multi_cell(0, 8, linha)
        pdf.ln(2)

    caminho = os.path.join(os.getcwd(), nome_arquivo)
    pdf.output(caminho)

    print(f"PDF criado com sucesso em: {caminho}")

# Gerar PDF
gerar_pdf_resumo(df_resumo, "outputs/Resumo_CodeNest.pdf")

PDF criado com sucesso em: c:\Users\User\Desktop\Projecto 2\Resumo_CodeNest.pdf

In [ ]:
df_maior_1.to_excel("outputs/maior_1.xlsx", index= False)
print("Excel criado com sucesso")

Excel criado com sucesso